name: EPAC PR Plan

# Run when a PR is opened or updated with new commits
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - 'Definitions/**'

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan tenant
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: TENANT-PLAN
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit